use_default_settings: true

general:
  debug: false
  instance_name: "PriestyAI Search"

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en-US"
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "priestyai_local_searxng_ultra_secure_secret_key_change_me"
  limiter: false
  image_proxy: false

engines:
  - name: unsplash
    disabled: true
  - name: openverse
    disabled: true
  - name: flickr
    disabled: true
  - name: pixabay
    disabled: true
  - name: wikimedia
    disabled: true
  - name: google images
    disabled: false
  - name: bing images
    disabled: false
  - name: duckduckgo images
    disabled: false
  - name: qwant images
    disabled: false
  - name: brave.images
    disabled: false